apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: default
  source:
    repoURL: 'https://github.com/grafana/helm-charts'
    path: charts/grafana
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true