apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend # Name of the deployment
  namespace: {{ .Values.explorer.namespace }}
spec:
  replicas: {{ .Values.explorer.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      containers:
        - name: {{ .Values.appName }}-backend # Name of the container
          image: {{ .Values.explorer.backend.container.image }} # Image name
          imagePullPolicy: {{ .Values.explorer.backend.container.imagePullPolicy }} # Image Pull Policy
          env: {{- range .Values.explorer.backend.container.env }}
          - name: {{ .name }}
            value: {{ .value | quote }} {{- end }}
          ports: {{ range .Values.explorer.backend.ports }}
          - containerPort: {{ .containerPort }} {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.explorer.namespace }}
spec:
  type: ClusterIP
  ports: 
  {{ range .Values.explorer.backend.ports }}
  - name: {{ .name }}
    port: {{ .containerPort }}
    targetPort: {{ .containerPort }} 
  {{ end }}
  selector:
    app: {{ .Values.appName }}-backend