apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-node-service
spec:
  type: ClusterIP
  selector:
    podName: {{ .Values.appName }}-pod
  ports:
  - name: {{ .Values.appName }}-node-service-port
    port: 8443
    targetPort: 8443