apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnailer
  namespace: {{ .Values.explorer.namespace }}
spec:
  replicas: {{ .Values.explorer.thumbnailer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-thumbnailer
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-thumbnailer
    spec:
      containers:
      - name: {{ .Values.appName }}-thumbnailer
        image: {{ .Values.explorer.thumbnailer.container.image }}
        imagePullPolicy: {{ .Values.explorer.thumbnailer.container.imagePullPolicy }}
        env: {{- range .Values.explorer.thumbnailer.container.env }}
        - name: {{ .name }}
          value: {{ .value | quote }} {{- end }}
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: accessKeyId
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secretAccessKey
        ports: {{ range .Values.explorer.thumbnailer.ports }}
        - containerPort: {{ .containerPort }} {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: thumbnailer
  namespace: {{ .Values.explorer.namespace }}
spec:
  ports:
  {{ range .Values.explorer.thumbnailer.ports }}
  - name: {{ .name }}
    port: {{ .containerPort }}
    targetPort: {{ .containerPort }}
  {{ end }}
  selector:
    app: {{ .Values.appName }}-thumbnailer
