apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend # Name of the deployment
  namespace: {{ .Values.explorer.namespace }}
  labels:
    app: {{ .Values.appName }}-backend
spec:
  replicas: {{ .Values.explorer.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      containers:
        - name: {{ .Values.appName }}-backend # Name of the container
          image: {{ .Values.explorer.backend.container.image }} # Image name
          imagePullPolicy: {{ .Values.explorer.backend.container.imagePullPolicy }} # Image Pull Policy
          env: {{- range .Values.explorer.thumbnailer.container.env }}
          - name: {{ .name }}
            value: "{{ .value }}" {{ end }}
          ports: {{ range $name, $value := .Values.explorer.thumbnailer.container.ports }} # Ports
          - containerPort: {{ .containerPort }} {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.explorer.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}-backend
  ports:
  - name: {{ .Values.appName }}-backend
    port: 8443
    targetPort: 8443