apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnailer
  namespace: {{ .Values.explorer.namespace }}
spec:
  replicas: {{ .Values.explorer.thumbnailer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-thumbnailer
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-thumbnailer
    spec:
      containers:
      - name: {{ .Values.appName }}-thumbnailer
        image: {{ .Values.explorer.thumbnailer.container.image }}
        imagePullPolicy: {{ .Values.explorer.thumbnailer.container.imagePullPolicy }}
        env: {{- range .Values.explorer.thumbnailer.container.env }}
        - name: {{ .name }}
          value: "{{ .value }}" {{ end }}
        ports: {{ range $name, $value := .Values.explorer.thumbnailer.container.ports }}
        - containerPort: {{ .containerPort }} {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: thumbnailer
  namespace: {{ .Values.explorer.namespace }}
spec:
  ports:
  - name: thumbnailer 
    port: 8441
    targetPort: 8441
  selector:
    app: {{ .Values.appName }}-thumbnailer
