apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend # Name of the deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      podName: {{ .Values.appName }}-pod
  template:
    metadata:
      labels:
        podName: {{ .Values.appName }}-pod
    spec:
      containers:
        - name: {{ .Values.appName }}-api # Name of the container
          image: {{ .Values.backendImage }} # Image name
          imagePullPolicy: Always
          env:
            - name: ENVIROMENT
              value: {{ .Values.environment }}
          ports:
            - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  type: ClusterIP
  selector:
    podName: {{ .Values.appName }}-pod
  ports:
  - name: {{ .Values.appName }}-service
    port: 8443
    targetPort: 8443