apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-node-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    podName: {{ .Values.appName }}-pod
  ports:
  - name: node
    port: 8443
    targetPort: 8443