apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend # Name of the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}-container # Name of the container
          image: lichfiet/file-explorer-backend:latest # Image name
          imagePullPolicy: Always
          env:
            - name: ENVIROMENT
              value: {{ .Values.environment }}
          ports:
            - containerPort: 8443