apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-node-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: node
    port: 8443
    targetPort: 8443