apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend # Name of the deployment
  labels:
    app: {{ .Values.appName }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-pod
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-pod
    spec:
      containers:
        - name: {{ .Values.appName }}-container # Name of the container
          image: {{ .Values.backendImage }} # Image name
          imagePullPolicy: Always
          env:
            - name: ENVIROMENT
              value: {{ .Values.environment }}
          ports:
            - containerPort: 8443