apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
spec:
  project: default
  source:
    repoURL: 'https://github.com/lichfiet/file-explorer-k8s'
    path: observability
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true
