apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: signoz-ingress
  namespace: {{ .Values.signoz.namespace }}
spec:
  entryPoints:
    - websecure
  tls:
    secretName: signoz-tls
  routes:
    - kind: Rule
      match: Host(`signoz.trevorlichfield.com`) && PathPrefix(`/`)
      priority: 15
      services:
        - name: observability-signoz-frontend
          port: 3301