apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: signoz-ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
    secretName: signoz-tls
  routes:
    - kind: Rule
      match: Host(`signoz.trevorlichfield.com`) && PathPrefix(`/`)
      priority: 12
      services:
        - name: observability-signoz-frontend
          port: 8443
