###############################################################################
# file-explorer
###############################################################################
appName: file-explorer
environment: development

rabbithost: rabbitmq.default.svc.cluster.local
rabbitport: 5672

redishost: redis.default.svc.cluster.local
redisport: 6379

rabbitmq:
  enabled: true

redis: 
  enabled: true


explorer:
  namespace: default
  backend:
    replicas: 1
    ports:
      - containerPort: 8443
        name: http
    container:
      image: lichfiet/file-explorer-backend:latest
      imagePullPolicy: Always
      env:
        - name: APP_NAME
          value: "file-explorer"
        - name: PORT
          value: "8443"
        - name: RABBITMQ_HOST
          value: "rabbitmq.default.svc.cluster.local"
        - name: REDIS_HOST      
          value: "redis.default.svc.cluster.local"   
        - name: LOG_LEVEL
          value: "debug"
        - name: OTEL_LOG_LEVEL
          value: "debug"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
          value: "http://observability-signoz-otel-collector.platform.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://observability-signoz-otel-collector.platform.svc.cluster.local:4318"
        - name: OTEL_NODE_RESOURCE_DETECTORS
          value: "env,host,os"
        - name: OTEL_SERVICE_NAME
          value: "file-explorer-backend"
        - name: NODE_OPTIONS
          value: "--require @opentelemetry/auto-instrumentations-node/register"
        - name: AWS_S3_BUCKET
          value: "file-explorer-s3-bucket"
  thumbnailer:
    replicas: 1
    ports:
      - containerPort: 8441
        name: http
    container:
      image: lichfiet/file-explorer-thumbnailer:latest
      imagePullPolicy: Always
      env:
        - name: ENVIRONMENT
          value: "development"
        - name: PORT
          value: "8441"
        - name: RABBITMQ_HOST
          value: "rabbitmq.default.svc.cluster.local"
        - name: REDIS_HOST
          value: "redis.default.svc.cluster.local"
        - name: LOG_LEVEL
          value: "debug"
        - name: OTEL_LOG_LEVEL
          value: "debug"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
          value: "http://observability-signoz-otel-collector.platform.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://observability-signoz-otel-collector.platform.svc.cluster.local:4318"
        - name: OTEL_NODE_RESOURCE_DETECTORS
          value: "env,host,os"
        - name: OTEL_SERVICE_NAME
          value: "file-explorer-thumbnailer"
        - name: NODE_OPTIONS
          value: "--require @opentelemetry/auto-instrumentations-node/register"
        - name: AWS_S3_BUCKET
          value: "file-explorer-s3-bucket"
        - name: THUMBNAIL_FILES_LOCATION
          value: "/usr/file/"
