###############################################################################
# Loki
###############################################################################

loki:
  deploymentMode: SingleBinary
  enabled: true
  auth_enabled: false
  commonConfig:
    replicationFactor: 2
  storage:
    type: s3
    bucketNames:
      chunks: "trevors-loki-test-chunks"
    s3:
      region: "us-west-1"
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
      accessKeyId: ${AWS_ACCESS_KEY_ID}
      insecure: true
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: s3
        index:
          prefix: loki_index_
          period: 24h
        schema: v13
        store: tsdb
  singleBinary:
    replicas: 2
  loki:
    storage:
      type: s3
      bucketNames:
        chunks: "trevors-loki-test-chunks"
      s3:
        region: "us-west-1"
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        insecure: true
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: s3
          index:
            prefix: loki_index_
            period: 24h
          schema: v13
          store: tsdb

  ingester:
    replicas: 0
  querier:
    replicas: 0
    maxUnavailable: 0
  queryFrontend:
    replicas: 0
    maxUnavailable: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
    maxUnavailable: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
    maxUnavailable: 0

  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0

  # Enable minio for storage
  minio:
    enabled: false

  # Zero out replica counts of other deployment modes
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0