###############################################################################
# Loki
###############################################################################

loki:
  deploymentMode: singleBinary
  enabled: true
  auth_enabled: false
  commonConfig:
    replicationFactor: 2
  storage:
    type: s3
    bucketNames:
      chunks: "trevors-loki-test-chunks"
    s3:
      region: "us-west-1"
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
      accessKeyId: ${AWS_ACCESS_KEY_ID}
      insecure: true
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: s3
        index:
          prefix: loki_index_
          period: 24h
        schema: v13
        store: tsdb
  singleBinary:
    replicas: 2
  loki:
    storage:
      type: s3
      bucketNames:
        chunks: "trevors-loki-test-chunks"
      s3:
        region: "us-west-1"
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        insecure: true
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: s3
          index:
            prefix: loki_index_
            period: 24h
          schema: v13
          store: tsdb