# ###############################################################################
# # Loki
# ###############################################################################

# loki:
#   loki:
#     auth_enabled: true
#     querier:
#       multi_tenant_queries_enabled: false
#     schemaConfig:
#       configs:
#       - from: 2023-07-01
#         store: tsdb
#         object_store: filesystem
#         schema: v13
#         index:
#           prefix: index_
#           period: 24h
#     storage:
#       type: s3
#       bucketNames:
#         chunks: "your-loki-chunks-bucket"
#         ruler: "your-loki-ruler-bucket"
#         admin: "your-loki-admin-bucket"

#   singleBinary:
#     replicas: 1
#   read:
#     replicas: 0
#   backend:
#     replicas: 0
#   write:
#     replicas: 0





#   # storage:
#   #   type: s3
#   #   bucketNames:
#   #     chunks: "trevors-loki-test-chunks"
#   #   s3:
#   #     region: "us-west-1"
#   #     secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
#   #     accessKeyId: ${AWS_ACCESS_KEY_ID}
#   #     insecure: true
