global:
  cloud: others
  clusterName: k3s-server
  deploymentEnvironment: production
otelCollectorEndpoint: observability-signoz-otel-collector.platform.svc.cluster.local:4317
otelCollectorInsecure: true
otelEndpoint: observability-signoz-otel-collector.platform.svc.cluster.local:4317
otelInsecure: true

alertmanager:
  replicaCount: 0

otelCollectorMetrics:
  replicaCount: 0

otelCollector:
  replicaCount: 2
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: name
          operator: NotIn
          values:
            - observability-signoz-otel-collector

presets:
  otlpExporter:
    enabled: true
  loggingExporter:
    enabled: true
    endpoint: observability-signoz-otel-collector.platform.svc.cluster.local:4318
    insecure: true
  logsCollection:
    enabled: true
    startAt: beginning
    includeFilePath: true
    includeFileName: false
    # This include path patterns for log files to be collected.
    # By default, all container logs are collected.
    # If whitelist is set, this list is ignored.
    include:
      - /var/log/pods/*/*/*.log
    # This can be used to exclude certain log files from being collected.
    # By default, kube-system and hotrod, locust pods are excluded.

signoz:
  enabled: true
  namespace: platform
