global:
  cloud: others
  clusterName: k3s-server
  deploymentEnvironment: production
otelCollectorEndpoint: observability-signoz-otel-collector.platform.svc.cluster.local:4317
otelCollectorInsecure: true
otelEndpoint: observability-signoz-otel-collector.platform.svc.cluster.local:4317
otelInsecure: true
presets:
  otlpExporter:
    enabled: true
  loggingExporter:
    enabled: true
    endpoint: observability-signoz-otel-collector.platform.svc.cluster.local:4318
    insecure: true
  loggingExporterKubernetes:
    enabled: true


signoz:
  enabled: true
  namespace: platform
