apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend # Name of the deployment
  namespace: {{ .Values.explorer.namespace }}
spec:
  replicas: {{ .Values.explorer.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      containers:
        - name: {{ .Values.appName }}-backend # Name of the container
          image: {{ .Values.explorer.backend.container.image }} # Image name
          imagePullPolicy: {{ .Values.explorer.backend.container.imagePullPolicy }} # Image Pull Policy
          env: {{- range .Values.explorer.backend.container.env }}
          - name: {{ .name }}
            value: {{ .value | quote }} {{- end }}
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: region
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: accessKeyId
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: secretAccessKey
          - name: K8S_NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports: {{ range .Values.explorer.backend.ports }}
          - containerPort: {{ .containerPort }} {{ end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8443
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.explorer.namespace }}
spec:
  type: ClusterIP
  ports: 
  {{ range .Values.explorer.backend.ports }}
  - name: {{ .name }}
    port: {{ .containerPort }}
    targetPort: {{ .containerPort }} 
  {{ end }}
  selector:
    app: {{ .Values.appName }}-backend