project: default
source:
  repoURL: 'https://github.com/lichfiet/file-explorer-k8s'
  path: .
  targetRevision: HEAD
  directory:
    jsonnet:
      extVars:
        - name: gyatt
          value: meow
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
info:
  - name: gyatt
    value: 'yes'