###############################################################################
# file-explorer
###############################################################################
appName: file-explorer
environment: development
namespace: backend
backendImage: lichfiet/file-explorer-backend:latest